name: firebasestarter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^0.14.3+1
  device_info: ^0.4.2+6
  firebase_analytics: ^6.2.0
  firebase_auth: ^0.18.3+1
  firebase_core: ^0.5.2+1
  firebase_crashlytics: ^0.2.3+1
  firebase_helpers: ^0.2.2
  firebase_messaging: ^7.0.3
  firebase_remote_config: ^0.4.2
  firebase_storage: ^5.1.0
  flutter_auth_buttons: ^0.9.0
  flutter_svg: ^0.18.0
  flutter_swiper: ^1.1.6
  google_fonts: ^1.1.0
  google_sign_in: ^4.5.3
  image_cropper: ^1.3.0
  image_picker: ^0.6.7+4
  package_info: ^0.4.3
  provider: ^4.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^0.1.2
  integration_test: ^1.0.0
  flutter_automation: ^1.3.2
  intl_translation: ^0.17.0
flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
